all: 
	g++ EDDM_Generator.cpp EDDM_Vector_Initialize.cpp Cube_Read.cpp Cube_Write.cpp Transition.cpp Square_Cubefile.cpp Parse_Cube_Header.cpp Voxel_Info.cpp File_Exists.cpp -o Electron_Density_Difference_Map_Calculator

 
