all: 
	clang++ TDMI_Generator.cpp Cube_Read.cpp Voxel_Info.cpp Square_Cubefile.cpp Cube_Norm.cpp Cube_To_Vector.cpp Cube_Dot_Product.cpp Distance_to_Voxel.cpp Orbital_Overlap.cpp Transition_Dipole_Moment.cpp -o Trans_Dipole_Calculator

 
